import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// Import local fonts, ensuring paths are relative to the public folder
const geistSans = localFont({
  src: "/fonts/GeistVF.woff", // Correct path for fonts in public folder
  variable: "--font-geist-sans",
  weight: "100 900", // Define the weight range of the font
});

const geistMono = localFont({
  src: "/fonts/GeistMonoVF.woff", // Correct path for fonts in public folder
  variable: "--font-geist-mono",
  weight: "100 900", // Define the weight range of the font
});

export const metadata: Metadata = {
  title: "Hackhaton", // Title of the app
  description: "Generated by create next app", // Description of the app
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
